### ISSUE TITLE
Adding EnableHighAvailabilityMode for Azure section

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-volumes-ontap-9101-relnotes#11]
Page: [What’s new in Cloud Volumes ONTAP 9.10.1](https://docs.netapp.com/us-en/cloud-volumes-ontap-9101-relnotes/reference-new.html)

Hi, 

I could only find the content for EnableHighAvailabilityMode in Azure just in the release notes section. I would be helpful, if this description could be added also in the normal CVO deployment section.
Especially, because Cloud manager does not list all required steps, but just "az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network"...missing: "az provider register -n Microsoft.Network"

Thx
Holger 

_To make these enhancements available to Cloud Volumes ONTAP, you need to enable a feature on your Azure subscription. An Azure user who has “Owner” privileges can enable the feature from the Azure CLI:

az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network
AzurecliCopy
Cloud Manager will prompt you with these details in an Action Required message for Cloud Volumes ONTAP 9.10.1 systems where the feature needs to be enabled on an Azure subscription.

Note the following:

There are no problems with the high availability of your Cloud Volumes ONTAP HA pair. This Azure feature works in concert with ONTAP to reduce the client observed application outage time for NFS protocols that result from unplanned failover events.

Enabling this feature is non-disruptive to Cloud Volumes ONTAP HA pairs.

Enabling this feature on your Azure subscription won’t cause issues to other VMs._

**Comment by kholger** [comment]
Hi Ben,

It also appears in Cloud Manager when new systems are deployed and the Azuer feature hasn't been activated before.
At least, this just happened to me on Monday deploying a system in customer environment.

Thx
Holger

**Comment by netapp-bcammett** [comment]
Holger,

I added the details in a new page:
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-azure-high-availability-mode.html

Please let me know if you think any additional changes are needed.

Thanks,
Ben

**Comment by kholger** [comment]
Great! Thank you, Ben!
